// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/service-hero/VariantA.tsx": () => import("../components/mockups/service-hero/VariantA.tsx"),
  "./components/mockups/service-hero/VariantB.tsx": () => import("../components/mockups/service-hero/VariantB.tsx"),
  "./components/mockups/service-hero/VariantC.tsx": () => import("../components/mockups/service-hero/VariantC.tsx"),
  "./components/mockups/service-hero/VariantD.tsx": () => import("../components/mockups/service-hero/VariantD.tsx")
};
